name: "2"
on:
  workflow_dispatch:
  pull_request:
jobs:
  important:
    environmentz: staging_environment
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
