name: "1"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  important:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
