name: CI-branch1

on:
  push:
    branches:
      - branch1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Run a one-line script
      run: echo this is my branch

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
