name: ci
on: push
jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -n 'hello world' > my-artifact.txt
      - uses: actions/upload-artifact@v2
        with:
          name: normal-artifact
          path: my-artifact.txt
      - uses: actions/upload-artifact@v2
        with:
          name: custom-artifact
          path: my-artifact.txt
          retention-days: 7
